export const hobbies = [
    "Reading",     
    "Writing",
    "Speaking",
    "Listening",
    "Traveling",
    "Cooking",
    "Gardening",
    "Painting",
    "Drawing",
    "Photography",
    "Dancing",
    "Singing",
    "Playing Guitar",
    "Playing Piano",
    "Playing Violin",
    "Running",
    "Swimming",
    "Hiking",
    "Fishing",
    "Camping",
    "Knitting",
    "Sewing",
    "Woodworking",
    "Pottery",
    "Origami",
    "Chess",
    "Board Games",
    "Video Games",
    "Yoga",
    "Meditation",
    "Martial Arts",
    "Collecting Stamps",
    "Collecting Coins",
    "Bird Watching",
    "Astronomy",
    "Calligraphy",
    "Scrapbooking",
    "Blogging",
    "Podcasting",
    "Surfing",
    "Skateboarding",
    "Snowboarding",
    "Skiing",
    "Rock Climbing",
    "Baking",
    "Makeup",
    "Fashion",
    "Magic Tricks",
    "Juggling",
    "Lego Building",
    "Robotics",
    "Programming",
    "3D Printing",
    "Model Building",
    "RC Cars",
    "Puzzle Solving",
];
